load_paths:
  - lib/assets/javascripts
  - test
  - jquery-rails:
    - vendor/assets/javascripts
  - actioncable:
    - app/assets/javascripts

logical_paths:
  - setup.js
  - cable_bindings.js
  - test.js

build:
  logical_paths:
    - cable_bindings.js
  path: dist
  js_compressor: uglifier