load_paths:
  - vendor/assets/javascripts
  - test

logical_paths:
  - setup.js
  - cable_bindings.js
  - test.js

gem_paths:
  jquery-rails:
    - vendor/assets/javascripts
  actioncable:
    - lib/assets/javascripts

build:
  logical_paths:
    - cable_bindings.js
  path: dist
  js_compressor: uglifier