load_paths:
  - lib/assets/javascripts
  - test
  - actioncable:
    - app/assets/javascripts

logical_paths:
  - cable_bindings.js
  - test.js

build:
  logical_paths:
    - cable_bindings.js
  path: dist
  js_compressor: uglifier